### ISSUE TITLE
November 2019 Status

### ISSUE THREAD

**Issue by gjscheer-ucd** [CSTARS/spatial-cimis#99]
### DWR PROD status
- [x] install latest spatial cimis code base
- [x] importing raw incoming data to GRASS
- [x] test solar parameter calculation
- [x] setup station data app key
- [x] test ETo calculation for GOES17
- [x] test ETo calculation for GOES15 format
- [x] create raster output
- [x] [g.cimis-dwr errors](https://github.com/CSTARS/spatial-cimis/issues/105)
- [x] fix file permission issue
- [x] [test CGI query](https://github.com/CSTARS/spatial-cimis/issues/106)
- [x] transfer GOES16 ETo from 10/23/2018 to 12/4/2019 and create GOES15 Eto products
- [x] transfer historical web output through 12/4/2019
- [x] as of 11/27/2019 begin automated GOES17 solar calculation
- [x] as of 12/4/2019 begin automated GOES17 ETo calculation

### DWR prod strategy
- monitoring
- Automated Sciences patching 12/4/2019 before sunrise
- GOES17 data cutover to be the go live date of 12/5/2019
- 11/14/ firewall rules may affect spatial API
- prod smoke test 11/18 to 11/22

### Status for g.cimis
- manual batch solar processing error
- [solar calc without PGM files Issue 90](https://github.com/CSTARS/spatial-cimis/issues/90)
- [final ssetr-G calc Issue 89](https://github.com/CSTARS/spatial-cimis/issues/89)
- [bad image check is implemented? Issue 66](https://github.com/CSTARS/spatial-cimis/issues/66)
- other updates?
- state of DWR dev & test?

### Status for cimis-goes-s
- [d.mon crashes- Issue 94](https://github.com/CSTARS/spatial-cimis/issues/94)
- [upgrading grass to 7.6 or 7.8 breaks r.solpos and r.heliosat compile - Issue 100](https://github.com/CSTARS/spatial-cimis/issues/100)

### Todo
- George will update the repo on test and dev

**Comment by qjhart** [comment]
## Prod - Data Assimilation

In order for prod to manage all data access, we need to get all the historical goes-15 data over.  It's also fine to get all the goes-17 test/dev data as well, these can overlap.  Transfer from the goes-15 production server is well defined in #93, although the tunnel issue (#42) is no longer required, you directly contact the goes-15 production server (mrsblapp20662.pr.water.ca.gov) 

Issue #93 moved data to the testing server, vut
